### ISSUE TITLE
Feature request: get length of a ChaseLev deque

### ISSUE THREAD

**Issue by robstewart57** [rrnewton/haskell-lockfree#32]
For implementing work stealing on networks of machines, a common technique is to use minimum watermarks. That is, on receiving a message from another PE to ask for work, the scheduler may want to know if it has a minimum number of sparks before they give some away.

The current ChaseLev implementation does not allow a scheduler to inspect the number of elements (sparks in this case). It might look like:

```
lengthQ :: ChaseLevDeque a -> IO Int
```

What are the costs of adding this function? Would it be lock-free?

The [cited paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.170.1097&rep=rep1&type=pdf) does report a `size()` method for the CircularArray class.

**Comment by treeowl** [comment]
It looks to me like this exists now, as `approxSize`. Can the ticket be closed?
