### ISSUE TITLE
[atomic-primops] Bugs and build problems on 7.10 RC1

### ISSUE THREAD

**Issue by jberryman** [rrnewton/haskell-lockfree#40]
We need `base` 4.8 If we manually ignore the base constraint, we get:

    jberryman /tmp/atomic-primops-0.6.1 » cabal install --only-dependencies -w /usr/local/bin/ghc-7.10.0.20141222 --allow-newer                                                                                                              1 ↵
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /tmp/atomic-primops-0.6.1/.cabal-sandbox
    Configuring primitive-0.5.4.0...
    Failed to install primitive-0.5.4.0
    Build log ( /tmp/atomic-primops-0.6.1/.cabal-sandbox/logs/primitive-0.5.4.0.log ):
    unrecognized 'configure' option `--disable-executable-profiling'
    cabal: Error: some packages failed to install:
    primitive-0.5.4.0 failed during the configure step. The exception was:
    ExitFailure 1

I have no idea where the hell that `--disable-executable-profiling` is coming from or why it's unrecognized.

**Comment by rrnewton** [comment]
Thanks, I'm taking a look.  By the way, what version of cabal-install was this?

**Comment by jberryman** [comment]
Thanks for looking into it. I just upgraded `cabal-install`:

    jberryman /tmp/atomic-primops-0.6.1 » cabal --version
    cabal-install version 1.20.0.6
    using version 1.20.0.3 of the Cabal library 

Aside from the `base` constraint, this seems like it is some sort of weird cabal issue or maybe something wonky with my install, but I don't know.

**Comment by jberryman** [comment]
(Oh, and a bit off topic, but I've been trying to figure out if there have been any interesting developments vis a vis `atomic-primops` in 7.10? Making them inline primops or something?)

**Comment by rrnewton** [comment]
With cabal install head (1.22.0.0), and 7.10 RC1 on linux, the atomic-primops library installs and passes tests for me on Linux, e.g. when I run with:

    cabal-1.22.0.0 install -w ~/opt/ghc-7.10-rc1/bin/ghc --run-tests ./ ./testing/

(I'm waiting for 7.10 to build on my laptop to test on Mac as well.)

However, I did see 2/107 test failures on this linux machine that need to be investigated.

```
casmutarray1: [Failed]
Unboxedbasic1_incrCounter: [Failed]
incrCounter returns the NEW value
expected: 10
 but got: 0    
```

I can't produce that error with GHC 7.8.3, so it seems to actually be a regression.

**Comment by rrnewton** [comment]
Huh, in some combinations of messing with sandboxes I can get this error:

```
Linking dist/dist-sandbox-c87b52cc/build/test-atomic-primops/test-atomic-primops ...
dist/dist-sandbox-c87b52cc/build/test-atomic-primops/test-atomic-primops-tmp/Test.dyn_o: In function `rlYU_info':
```

But I haven't reproduced the same error as you got with cabal-1.20.0.6.  Instead I'm currently having problems like this:

```
cabal-1.20.0.6
cabal-1.20.0.6 install ./ ./testing/ --run-tests -w ~/opt/ghc-7.10-rc1/bin/ghc
ghc: ghc no longer supports single-file style package databases (dist/dist-sandbox-c87b52cc/package.conf.inplace) use 'ghc-pkg init'
```

**Comment by rrnewton** [comment]
Small update.  If I build without a sandbox, I get to the same point with cabal-1.20.0.6 as I did with the HEAD version.  That is, it installs fine and 2/107 tests fail.

**Comment by rrnewton** [comment]
I factored out the failure of `Unboxedbasic1_incrCounter` into issue #41.

I still need to look at the `casmutarray1` failure.

**Comment by jberryman** [comment]
Thanks for looking into this so quickly. FWIW the main issue I was having was unrelated to atomic-primops (I describe what I had to do to get a working 7.10 [here](http://www.reddit.com/r/haskell/comments/2r5o7h/workedforme_instructions_for_trying_out_ghc_710/)). I'll close this since you've released the updated base constraint version, and you have a separate ticket for the issue you uncovered.

**Comment by jberryman** [comment]
Sorry, changed my mind; I'll let you close this when you're ready :)

**Comment by rrnewton** [comment]
Sure, either way, I see this ticket as for the cabal incompatibility you cited.  So I changed the title to that effect.  Currently I have not successfully reproduced that using cabal-install 1.20.0.6 / Cabal 1.20.0.3.  Can you get that same error reproducably?

I also added #42 for the other failed test and a "ghc-7.10" milestone for all issues related to GHC 7.10 support.
