### ISSUE TITLE
atomic-primops: ghc 8 support needed

### ISSUE THREAD

**Issue by ekmett** [rrnewton/haskell-lockfree#55]
I'm updating all my packages for ghc 8-rc1 support, and am stuck on all of them that depend on `atomic-primops`. This seems likely to just be a bump and push.

**Comment by rrnewton** [comment]
Thanks, @osa1 or @dreamlinuxer, could you push this out?  I'm swamped till Tues morning.

**Comment by osa1** [comment]
I started working on this in ghc-8.0 branch, and on the way I found a GHC bug and reported here: https://ghc.haskell.org/trac/ghc/ticket/11444

I'll see if there's an obvious problem to solve but otherwise we may have to wait until this is fixed, as I don't have a lot of time for this. (or maybe we can find a workaround?)

**Comment by rrnewton** [comment]
Darn, so much for the simple verison bump.

**Comment by osa1** [comment]
This package is actually broken even with GHC 7.8. Try to compile with `--ghc-options=-dcore-lint`.

**Comment by rrnewton** [comment]
OK, right now there's at least a small fix that we can do that affects all `ghc-7.11.XYZ` and `ghc-8.1.XYZ` dev builds we're doing. 

This has to do with tolerance of redundant type sigs for foreign imports: https://github.com/rrnewton/haskell-lockfree/commit/19730d601dae28530fb0945688bdc6d9cc535768

**Comment by rrnewton** [comment]
Pushed that small fix in a minor release: https://hackage.haskell.org/package/atomic-primops-0.8.0.3

**Comment by RyanGlScott** [comment]
I'm closing this since the current version of `atomic-primops` supports GHC 8, and https://ghc.haskell.org/trac/ghc/ticket/11444 has been dealt with separately.
