### ISSUE TITLE
[chaselev-deque] stackage availability

### ISSUE THREAD

**Issue by tmcdonell** [rrnewton/haskell-lockfree#63]
Any chance of getting chaselev-deque on stackage? It's a dependency of accelerate-llvm.

**Comment by RyanGlScott** [comment]
I think this could be arranged. There are several @rrnewton packages that have been implicitly brought into Stackage already via `criterion` and others (I count `atomic-primops`, `abstract-deque`, `abstract-par`, `monad-par`, and `thread-local-storage`). It would be nice to have them put on Stackage explicitly, though.

@rrnewton, do you object if I add these packages to Stackage under your name? Or, if not that, under my name (which I've already done with `thread-local-storage`)?

**Comment by RyanGlScott** [comment]
I talked with @rrnewton, and he agreed to let me put these packages under my name on Stackage. I've opened https://github.com/fpco/stackage/issues/2467 to do just this.

**Comment by RyanGlScott** [comment]
https://github.com/fpco/stackage/issues/2467 has been merged, so `chaselev-deque` should be in Stackage nightly soon.

**Comment by tmcdonell** [comment]
Thanks! (:
