### ISSUE TITLE
Cut a new atomic-primops release for GHC 8.2.1

### ISSUE THREAD

**Issue by RyanGlScott** [rrnewton/haskell-lockfree#66]

**Comment by tmcdonell** [comment]
FWIW I have been using 7ac36d701caa759a9f9defd418d8959f4e9c6ef0 with the release candidates and haven't encountered any problems.

**Comment by RyanGlScott** [comment]
OK, I just obtained Hackage access for this package.

I've uploaded [`atomic-primops-0.8.1`](http://hackage.haskell.org/package/atomic-primops-0.8.1) to Hackage.
