### ISSUE TITLE
Recursion in haddocks of `atomic-primops`

### ISSUE THREAD

**Issue by qrilka** [rrnewton/haskell-lockfree#68]
In haddocks for `atomicModifyIORefCAS` I see
```
A drop-in replacement for `atomicModifyIORefCAS` that...
```
How is it possible? I there some fixpoint operator for haddocks? :)

**Comment by RyanGlScott** [comment]
Good catch, thanks. Fixed in https://github.com/rrnewton/haskell-lockfree/commit/b13b97ec1176a4a9e6db0b871c220abcb054db41.
